name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set up Emscripten
        run: |
          wget https://github.com/emscripten-core/emsdk/archive/main.tar.gz
          tar -xf main.tar.gz
          emsdk-main/emsdk install latest
          emsdk-main/emsdk activate latest
          emsdk-main/emsdk construct_env > tmp
          source tmp
          for i in `sed -n 's/^export \(.*\)=.*$/\1/p' tmp`
          do
            echo $i"<<EOF" >> $GITHUB_ENV
            echo ${!i} >> $GITHUB_ENV
            echo EOF >> $GITHUB_ENV
          done
      - name: Install dependencies
        run: npm ci
      - name: Build xterm-pty
        run: npm run build
      - name: Build tests
        run: npm run build:tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
